title: "Logan Beauty"
logo: img/nny.jpg
description: "Avec des produits d'extracts naturels reprenez controle de votre santé Fertilité Faiblesse sexuelle VIH Cancer Fibromes Diabète etc la Solution est ici/Take control of your health with natural extracts! Tackling Fertility, Sexual Weakness, HIV, Cancer, Fibroids Diabet & more. Your solution is here"
show_downloads: true 
theme: jekyll-theme-minimal
lang: fr
